# Generated by Django 2.2.14 on 2020-07-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoadon',
            old_name='IDphong',
            new_name='IDPhong',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='NgayThanhToan',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='TongTien',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='NgayThue',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='NgayTra',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='TinhTrang',
        ),
        migrations.RemoveField(
            model_name='thongkedoanhthu',
            name='DoanhThu',
        ),
        migrations.RemoveField(
            model_name='thongkedoanhthu',
            name='Thang',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='dis_CMND',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='dis_SDT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='dis_DonGia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='CMND',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='SDT',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='TenKhachHang',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='loaikhachhang',
            name='TenLoaiKhachHang',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='loaiphong',
            name='TenLoaiPhong',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='DonGia',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='phong',
            name='TenPhong',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='PHIEUDATPHONG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayThue', models.DateTimeField()),
                ('NgayTra', models.DateTimeField()),
                ('IDKhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.KHACHHANG')),
                ('IDphong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PHONG')),
            ],
        ),
    ]
