# Generated by Django 2.2.14 on 2020-07-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200710_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='dis_CMND',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='dis_SDT',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='dis_DonGia',
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='CMND',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='SDT',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='DonGia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
